### Create a new patient
POST http://localhost:8080/api/patients
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "dateOfBirth": "1990-01-15",
  "contactNumber": "1234567890",
  "emailAddress": "john.doe@example.com",
  "gender": "Male"
}

###

### Get all patients
GET http://localhost:8080/api/patients

###

### Get a specific patient by ID
GET http://localhost:8080/api/patients/683c803378a30fadf63e03a3

###

### Update the patient by ID
PUT http://localhost:8080/api/patients/683c803378a30fadf63e03a3
Content-Type: application/json

{
  "firstName": "Johnathan",
  "lastName": "Doe",
  "dateOfBirth": "1990-01-15",
  "contactNumber": "9876543210",
  "emailAddress": "johnathan.doe@example.com",
  "gender": "Male"
}

###

### Delete the patient by ID
DELETE http://localhost:8080/api/patients/683c803378a30fadf63e03a3
